# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raspicat_vla.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raspicat_vla.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12raspicat_vla.proto\x12\x0fraspicat_vla.v1\"\xe5\x01\n\x0bObservation\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x17\n\x0f\x63\x61pture_time_ns\x18\x02 \x01(\x04\x12\x12\n\nimage_jpeg\x18\x03 \x01(\x0c\x12\x13\n\x0bimage_width\x18\x04 \x01(\r\x12\x14\n\x0cimage_height\x18\x05 \x01(\r\x12\'\n\x04goal\x18\x06 \x01(\x0b\x32\x19.raspicat_vla.v1.GoalSpec\x12\x32\n\x0c\x63urrent_pose\x18\x07 \x01(\x0b\x32\x17.raspicat_vla.v1.Pose2DH\x00\x88\x01\x01\x42\x0f\n\r_current_pose\"\xc8\x01\n\x08GoalSpec\x12,\n\x04mode\x18\x01 \x01(\x0e\x32\x1e.raspicat_vla.v1.GoalSpec.Mode\x12\'\n\x04pose\x18\x02 \x01(\x0b\x32\x17.raspicat_vla.v1.Pose2DH\x00\x12\x0e\n\x04text\x18\x03 \x01(\tH\x00\x12\x14\n\nimage_jpeg\x18\x04 \x01(\x0cH\x00\x12\x10\n\x08\x66rame_id\x18\x05 \x01(\t\"%\n\x04Mode\x12\x08\n\x04POSE\x10\x00\x12\x08\n\x04TEXT\x10\x01\x12\t\n\x05IMAGE\x10\x02\x42\x06\n\x04goal\"-\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\"\xbe\x01\n\x0f\x41\x63tionEmbedding\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x16\n\x0eserver_time_ns\x18\x02 \x01(\x04\x12\x12\n\nnum_tokens\x18\x03 \x01(\r\x12\x11\n\tembed_dim\x18\x04 \x01(\r\x12\x16\n\x0e\x65mbedding_fp16\x18\x05 \x01(\x0c\x12\x14\n\x0cinference_ms\x18\x06 \x01(\x02\x12\x1a\n\rmodel_version\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_model_version\"\x12\n\x10ModelInfoRequest\"|\n\tModelInfo\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x12\n\nnum_tokens\x18\x03 \x01(\r\x12\x11\n\tembed_dim\x18\x04 \x01(\r\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\x12\r\n\x05ready\x18\x06 \x01(\x08\x32\xae\x01\n\nVLAService\x12Q\n\x0bStreamInfer\x12\x1c.raspicat_vla.v1.Observation\x1a .raspicat_vla.v1.ActionEmbedding(\x01\x30\x01\x12M\n\x0cGetModelInfo\x12!.raspicat_vla.v1.ModelInfoRequest\x1a\x1a.raspicat_vla.v1.ModelInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raspicat_vla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION']._serialized_start=40
  _globals['_OBSERVATION']._serialized_end=269
  _globals['_GOALSPEC']._serialized_start=272
  _globals['_GOALSPEC']._serialized_end=472
  _globals['_GOALSPEC_MODE']._serialized_start=427
  _globals['_GOALSPEC_MODE']._serialized_end=464
  _globals['_POSE2D']._serialized_start=474
  _globals['_POSE2D']._serialized_end=519
  _globals['_ACTIONEMBEDDING']._serialized_start=522
  _globals['_ACTIONEMBEDDING']._serialized_end=712
  _globals['_MODELINFOREQUEST']._serialized_start=714
  _globals['_MODELINFOREQUEST']._serialized_end=732
  _globals['_MODELINFO']._serialized_start=734
  _globals['_MODELINFO']._serialized_end=858
  _globals['_VLASERVICE']._serialized_start=861
  _globals['_VLASERVICE']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
