# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import raspicat_vla_pb2 as raspicat__vla__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in raspicat_vla_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VLAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInfer = channel.stream_stream(
                '/raspicat_vla.v1.VLAService/StreamInfer',
                request_serializer=raspicat__vla__pb2.Observation.SerializeToString,
                response_deserializer=raspicat__vla__pb2.ActionEmbedding.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/raspicat_vla.v1.VLAService/GetModelInfo',
                request_serializer=raspicat__vla__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=raspicat__vla__pb2.ModelInfo.FromString,
                _registered_method=True)


class VLAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamInfer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VLAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInfer': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=raspicat__vla__pb2.Observation.FromString,
                    response_serializer=raspicat__vla__pb2.ActionEmbedding.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=raspicat__vla__pb2.ModelInfoRequest.FromString,
                    response_serializer=raspicat__vla__pb2.ModelInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raspicat_vla.v1.VLAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raspicat_vla.v1.VLAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VLAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamInfer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/raspicat_vla.v1.VLAService/StreamInfer',
            raspicat__vla__pb2.Observation.SerializeToString,
            raspicat__vla__pb2.ActionEmbedding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raspicat_vla.v1.VLAService/GetModelInfo',
            raspicat__vla__pb2.ModelInfoRequest.SerializeToString,
            raspicat__vla__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
